name = "slack-mod-reporter"
main = "slack-moderation-worker.js"
compatibility_date = "2024-10-24"

# Use workers.dev subdomain for deployment
workers_dev = true

# Environment variables (secrets should be set via: wrangler secret put SECRET_NAME)
# SLACK_BOT_TOKEN - Set via: wrangler secret put SLACK_BOT_TOKEN
# MOD_CHANNEL_ID - Set via: wrangler secret put MOD_CHANNEL_ID

# Uncomment and configure if using a custom domain instead of workers.dev
# routes = [
#   { pattern = "yourdomain.com/slack/report-behavior", zone_name = "yourdomain.com" }
# ]
